# IMG
FROM nsqio/nsq

# WHO
MAINTAINER boxu@yvhai.com


# 创建用户
# RUN groupadd -g 1000 foobar \
#     && useradd -g foobar -u 1000 -s /bin/bash foobar \
#     && echo "foobar ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/99-yh-foobar


# 接口
WORKDIR /demo
# EXPOSE 22
# VOLUME [ "/demo", "/project", "/data"]


# clean


# CMD
# ENTRYPOINT [ "/usr/sbin/init" ] 
